apiVersion: apps/v1 # Specifies the API version for the Deployment resource
kind: Deployment # Defines this resource as a Deployment
metadata:
  name: my-node-app # Unique name for the Deployment instance
spec:
  replicas: 2 # Desired number of Pods to run, maintaining high availability
  selector:
    matchLabels:
      app: node-app # Ensures Pods with this label are managed by this Deployment

  template:
    metadata:
      labels:
        app: node-app # Label applied to each Pod managed by this Deployment

    spec:
      containers:
        - name: node-app # Container name within the Pod
          image: philippaul/node-demo-app:01 # Container image for the Node.js app
          ports:
            - containerPort: 3000 # Exposes port 3000 of the container

