apiVersion: v1
kind: Service
metadata:
  name: service-my-node-app # Unique name for the Service
spec:
  selector:
    app: node-app # Selector to match the label on the Deployment's Pods
  ports:
    - protocol: TCP
      port: 8080 # External port for the Service
      targetPort: 3000 # Port on the Pod to forward traffic to
  type: LoadBalancer # Expose the Service externally using a load balancer
